# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
# To update generated code, run `pub run build_runner build`
targets:
  $default:
    sources:
      - 'lib/account_api.dart'
      - 'lib/admin_api.dart'
      - 'lib/package_api.dart'
      - 'lib/page_data.dart'
      - 'lib/publisher_api.dart'
      - 'lib/task_api.dart'
