name: pub_dev
author: Dart Team <misc@dartlang.org>
description: The pub.dartlang.org website.
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  _popularity:
    path: ../pkg/_popularity
  neat_cache: ^1.0.0
  appengine: '^0.11.0' # TODO before upgrading: update configuration.uploadSignerServiceAccount for prod
  args: '>=0.13.7 <2.0.0'
  basics: ^0.4.0
  client_data:
    path: ../pkg/client_data
  convert: '^2.0.0'
  crypto: '^2.0.2'
  fake_gcloud:
    path: ../pkg/fake_gcloud
  gcloud: '^0.7.3'
  googleapis: '^0.55.0'
  googleapis_auth: ^0.2.4
  html: '>=0.12.0 <0.15.0'
  http: '>=0.12.0 <0.13.0'
  http_parser: '>=3.1.1 <4.0.0'
  intl: '^0.16.0'
  json_annotation: '^3.0.0'
  logging: '>=0.9.3 <1.0.0'
  markdown: ^3.0.0
  meta: ^1.1.2
  mime: '>=0.9.3 <0.10.0'
  mustache: ^1.0.0
  path: '^1.4.2'
  pool: '^1.3.4'
  pub_dartdoc_data:
    path: ../pkg/pub_dartdoc_data
  pub_package_reader:
    path: ../pkg/pub_package_reader
  pub_semver: '>=1.2.2 <2.0.0'
  pubspec_parse: ^0.1.4
  shelf: '^0.7.9'
  shelf_router: ^0.7.4
  stack_trace: ^1.9.2
  stream_transform: ^1.1.0
  watcher: ^0.9.7
  yaml: '^2.1.12'
  # pana version to be pinned
  pana: '0.14.9'
  # 3rd-party packages with pinned versions
  archive: '2.0.11'
  buffer: '1.0.7'
  mailer: '3.2.1'
  sanitize_html: '1.4.1'
  ulid: '1.1.0'
  http_retry: '0.1.1+3'
  api_builder:
    path: ../pkg/api_builder
  chunked_stream: ^1.1.0
  pub_worker:
    path: ../pkg/pub_worker

dependency_overrides:
  _discoveryapis_commons: ^0.2.0 # can be removed when package:gcloud is upgraded

dev_dependencies:
  build_runner: '^1.0.0'
  build_verify: ^1.1.1
  coverage: any # test already depends on it
  json_serializable: '^3.0.0'
  pub_validations:
    path: ../pkg/pub_validations
  shelf_router_generator: ^0.7.2+3
  source_gen: '^0.9.0'
  test: ^1.2.0
  xml: ^4.5.0
