# See https://pub.dev/packages/mono_repo for details on this file
dart:
  - 2.10.0

stages:
  - smoke_test:
    - group:
        - dartfmt
        - dartanalyzer: --fatal-infos --fatal-warnings bin/ lib/
  - unit_test:
      - test: --run-skipped --concurrency=1 `find test -name "*_test\\.dart" | sort | sed -n '0~3p'`
      - test: --run-skipped --concurrency=1 `find test -name "*_test\\.dart" | sort | sed -n '1~3p'`
      - test: --run-skipped --concurrency=1 `find test -name "*_test\\.dart" | sort | sed -n '2~3p'`
