name: pub_worker
description: Worker for pana and dartdoc analysis for pub.dev
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies: 
  json_annotation: '^3.0.0'
  jsontool: ^1.0.1
  pana: ^0.14.9
  meta: ^1.1.5
  api_builder:
    path: ../api_builder
  client_data:
    path: ../client_data
  http: ^0.12.0
  http_parser: ^3.1.4
  retry: ^3.0.1
  logging: ^0.11.4

dev_dependencies:
  test: ^1.5.1
  build_runner: '^1.0.0'
  json_serializable: '^3.0.0'
  shelf: ^0.7.9
  shelf_router: ^0.7.4
