name: Tests
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
  DART_SDK_VERSION: '3.8.0'
permissions: read-all

jobs:
  testpkg:
    strategy:
      matrix:
        package:
        - api_builder
        - code_coverage
        - fake_gcloud
        - fake_pub_server
        - indexed_blob
        - _popularity
        - pub_dartdoc
        - pub_dartdoc_data
        - pub_integration
        - pub_package_reader
        - _pub_shared
        - pub_validations
        - pub_worker
        - web_app
        - web_css
    name: Test ${{package}}
    runs-on: ubuntu-latest
    steps:
    - name: Cache PUB_CACHE
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
      with:
        path: ~/.pub-cache
        key: ${{runner.os}}-pub-cache
    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
      with:
        sdk: ${{env.DART_SDK_VERSION}}
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - run: dart pub get
    - run: dart analyze --fatal-infos .
      working-directory: pkg/${{package}}
    - run: dart format --output=none --set-exit-if-changed .
      working-directory: pkg/${{package}}
    - run: dart test --run-skipped
      working-directory: pkg/${{package}}
